common/models/Tovar.php
<?php

namespace common\models;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tovar".
 *
 * @property int $id
 * @property string $name
 * @property string $item_values
 * @property string $description
 * @property int $img_id
 * @property string $subcategory_name
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $link_name
 * @property string $short_name
 * @property integer $sort
 */
class Tovar extends ActiveRecord
{

    public $main_category = 0;
    public $create_news = 0;
    const SCENARIO_CREATE = 'create';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tovar';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description', 'subcategory_name', 'link_name', 'short_name', 'item_values'], 'string'],
            [['short_name', 'name'], 'required'],
            [['main_category', 'subcategory_name'], 'required', 'on' => self::SCENARIO_CREATE],
            [['create_news', 'sort'], 'integer'],
            [['link_name'], 'unique'],
            [['img_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Полное название товара'),
            'description' => Yii::t('app', 'Описание'),
            'item_values' => Yii::t('app', 'Основное описание'),
            'img_id' => Yii::t('app', 'Изображение'),
            'main_category' => Yii::t('app', 'Основная категория'),
            'subcategory_name' => Yii::t('app', 'Подкатегория'),
            'link_name' => Yii::t('app', 'Английское имя для ссылки'),
            'short_name' => Yii::t('app', 'Короткое имя для карточки товара'),
            'create_news' => Yii::t('app', 'Создать новость при добавлении товара?'),
            'sort' => Yii::t('app', 'Порядок сортировки'),
            'created_at' => Yii::t('app', 'Создано'),
            'updated_at' => Yii::t('app', 'Изменено')
        ];
    }

    /**
     * Получить изображение
     * @return string
     */
    public function getImage()
    {
        /** @var Images $image */
        $image = Images::find()->where(['id' => $this->img_id])->one();

        if ($image) {
            return '/uploads' . $image->path .'/'. $image->name .'.'. $image->ext;
        } else {
            return false;
        }
    }

    /**
     * Получить 3 рандомных товара из категории обуви или одежды
     */
    public function getRandomlyItems()
    {
        // Найдем все категории у которых родительская группа обувь или одежда
        $modelCat = Subcategory::find()->where(['name' => $this->subcategory_name])->one();
        $modelCatAll = Subcategory::find()->where(['main_category_id' => $modelCat->main_category_id])->asArray()->all();
        $allIds = ArrayHelper::getColumn($modelCatAll, 'name');

        $allItems = Tovar::find()->where(['in','subcategory_name', $allIds])->asArray()->all();

        $allIds = ArrayHelper::getColumn($allItems, 'id');

        // Если в массиве содержится товар на странице которого мы находимся, убрать его из списка
        if (($key = array_search($this->id, $allIds)) !== false){
            unset($allIds[$key]);
        }

        // Посчитаем кол-во и выберем 3 рандомных из них
        $countItems = count($allIds);

        if ($countItems > 3){
            $keys = array_rand($allIds, 3);

            $ids = [];
            foreach ($keys as $key) {
                $ids[] = $allIds[$key];
            }
        } else {
            $ids = $allIds;
        }

        return Tovar::find()->where(['in', 'id', $ids])->all();
    }
}

backend/controllers/TovarController.php
<?php

namespace backend\controllers;

use backend\models\UploadForm;
use common\models\AppFunctions;
use common\models\Images;
use common\models\MainMenuCategory;
use common\models\News;
use common\models\Subcategory;
use common\models\TovarSearch;
use Yii;
use common\models\Tovar;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * TovarController implements the CRUD actions for Tovar model.
 */
class TovarController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Tovar models.
     * @return mixed
     */
    public function actionIndex()
    {
//        $dataProvider = new ActiveDataProvider([
//            'query' => Tovar::find(),
//            'sort' => [
//                'defaultOrder' => ['created_at' => SORT_DESC]
//            ]
//        ]);

        $dataSearch = new TovarSearch();
        $dataProvider = $dataSearch->search(Yii::$app->request->queryParams);
//        $dataProvider->pagination->pageSize = 1;


        $mainCategoryQuery = MainMenuCategory::find()->asArray()->all();
        $mainCategory = ArrayHelper::map($mainCategoryQuery, 'id', 'name');

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'dataSearch' => $dataSearch,
            'mainCategory' => $mainCategory
        ]);
    }

    /**
     *Функция возвращает массив элиментов
     * @param null $filter
     * @return array
     */
    public function actionSubcat($filter = null) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $out = self::getSubCatList($cat_id, $filter);
                // the getSubCatList function will query the database based on the
                // cat_id and return an array like below:
                // [
                //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                // ]

                return ['output'=>$out, 'selected'=>''];
            }
        }
        return ['output'=>'', 'selected'=>''];
    }

    /**
     * @param $cat_id
     * @param null $filter
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getSubCatList($cat_id, $filter = null)
    {
        if ($filter) {
            $array = Subcategory::find()->select(['name', 'id'])->where(['main_category_id' => $cat_id])->all();

            foreach ($array as $key => $value) {
                $array[$key]->id = $value->name;
            }
            return $array;
        } else {
            return Subcategory::find()->select(['id', 'name'])->where(['main_category_id' => $cat_id])->all();
        }
    }

    /**
     * Displays a single Tovar model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        // Заполняем массив для вывода detailView только заполненных полей
        $view_arr = [];
        foreach ($model as $key => $attr) {
            if ($attr != '') {
                $view_arr[] = $key;
            }
        }


        // Так как массив компонентов формируеться динамически, то мы не можем указать во view как выводить дату,
        // перезапишем поля заранее
        $model->created_at = date('d.m.Y', $model->created_at);
        $model->updated_at = date('d.m.Y', $model->updated_at);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Tovar model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Tovar();
        $model->scenario = Tovar::SCENARIO_CREATE;

        // Прикрепим поведение с параметрами изображения для последующей обработки
        $img = new UploadForm('Product');
        $img->scenario = UploadForm::SCENARIO_CREATE;

        $mainCategoryQuery = MainMenuCategory::find()->asArray()->all();

        $mainCategory = ArrayHelper::map($mainCategoryQuery, 'id', 'name');

        $allSubCategoriesQuery = Subcategory::find()->asArray()->all();
        $allSubCategories = ArrayHelper::map($allSubCategoriesQuery, 'name', 'name');

        if ($img->load(Yii::$app->request->post())) {

            $img->imageFile = UploadedFile::getInstance($img, 'imageFile');
            if ($img->imageFile){
                $model->img_id = $img->upload();
            }
        }

        $model->created_at = $model->updated_at = time();
        if ($model->load(Yii::$app->request->post())) {

            $model->link_name = str_replace(AppFunctions::getRus(), AppFunctions::getEng(), $model->short_name);

            // Если стоит галка создать новость
            if ($model->create_news == 1) {
                $news = new News();
                $news->link_name = '/catalog/' . $model->link_name;
                $news->image_id = $model->img_id;
                $news->title = $model->short_name;
                $news->text = $model->description;
                $news->create_at = $news->update_at = time();
                $news->save();
            }

            // Найдем имя категории и перезапишем переменную
            $model->subcategory_name = Subcategory::findOne($model->subcategory_name)->name;

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'subcategory' => $allSubCategories,
            'mainCategory' => $mainCategory,
            'img' => $img
        ]);
    }

    /**
     * Updates an existing Tovar model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        // Прикрепим поведение с параметрами изображения для последующей обработки
        $img = new UploadForm('Product');

        $imageView = Images::findOne($model->img_id);

        $mainCategoryQuery = MainMenuCategory::find()->asArray()->all();

        $mainCategory = ArrayHelper::map($mainCategoryQuery, 'id', 'name');

        $allSubCategoriesQuery = Subcategory::find()->asArray()->all();
        $allSubCategories = ArrayHelper::map($allSubCategoriesQuery, 'name', 'name');

        // Загрузка изображения
        if ($img->load(Yii::$app->request->post())) {
            $img->imageFile = UploadedFile::getInstance($img, 'imageFile');

            if ($img->imageFile){
                $model->img_id = $img->upload();
            }
        }

        $model->updated_at = time();
        if ($model->load(Yii::$app->request->post())) {

            $model->link_name = str_replace(AppFunctions::getRus(), AppFunctions::getEng(), $model->short_name);

            if (mb_strlen($model->subcategory_name) < 3) {
                // Найдем имя категории и перезапишем переменную
                $model->subcategory_name = Subcategory::findOne($model->subcategory_name)->name;
            }

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'subcategory' => $allSubCategories,
            'mainCategory' => $mainCategory,
            'img' => $img,
            'imageView' => $imageView
        ]);
    }

    /**
     * Изменияем sort
     * @param $id
     * @throws NotFoundHttpException
     */
    public function actionSort($id){
        $model = $this->findModel($id);
        $model->sort = Yii::$app->request->post('sort');
        $model->save();
    }

    /**
     * Deletes an existing Tovar model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tovar model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tovar the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tovar::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/tovar/_form.php
<?php

use common\models\Images;
use common\models\Tovar;
use dosamigos\ckeditor\CKEditor;
use kartik\depdrop\DepDrop;
use vova07\imperavi\Widget;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Tovar */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tovar-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'short_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'sort')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'main_category')->dropDownList($mainCategory,
        ['id' => 'mainCat', 'prompt'=>'Выберете категорию'])->label('Главная категория')?>

    <?= $form->field($model, 'subcategory_name')->widget(DepDrop::classname(), [
        'options'=>['id'=>'subcat-id'],
        'pluginOptions'=>[
            'depends'=>['mainCat'],
            'placeholder'=>'Выберете подкатегорию',
            'url' => Url::to(['/tovar/subcat'])
        ]
    ]); ?>
    <?php if ($model->scenario !== Tovar::SCENARIO_CREATE):?>
    <button type="button" id="change-cat" class="btn btn-primary">Изменить категории</button>
    <?php endif;?>

    <?php
    echo $form->field($model, 'item_values')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'imageUpload' => Url::to(['/files/upload']),
            'plugins' => [
                'clips',
                'fullscreen',
                'imagemanager',
            ],
            'clips' => [
                ['Текст в квадрате', '<span class="label-red">Текст в квадрате</span>'],
            ],
        ],
    ]);?>
    <?php
    echo $form->field($model, 'description')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'imageUpload' => Url::to(['/files/upload']),
            'plugins' => [
                'clips',
                'fullscreen',
                'imagemanager',
            ],
            'clips' => [
                ['Текст в квадрате', '<span class="label-red">Текст в квадрате</span>'],
            ],
        ],
    ]);?>
    <?= $form->field($model, 'create_news',  ['inputOptions' => ['class' => 'form-group others'],
            'labelOptions' => [ 'class' => 'custom-control-label others']])->checkbox(['class' => 'custom-control-input others',
            'template'=> '<div class="custom-control custom-switch">{input}{label}</div>'])?>

    <?php if ($model->scenario !== Tovar::SCENARIO_CREATE):?>
    <img src="<?= 'http://cc59539.tmweb.ru/uploads' . $imageView->path .'/'. $imageView->name .'.'. $imageView->ext;?>"
         width="150" height="150" alt="">
    <?php endif;?>
    <?= $form->field($img, 'imageFile', ['options' => ['class' => 'form-group others']])->fileInput() ?>

    <div class="form-group others">
        <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end();?>


    <?php if ($model->scenario == Tovar::SCENARIO_CREATE):?>
    <script>
        let select = $('#subcat-id');
        let others = $('.others');
        let i = 0;


        select.on('change', function () {
            let selected = $('#subcat-id option:selected');
            if (selected.text()){

                $.each(others, function (index, value) {
                    value.style = 'display:block';
                });
            }

            if (!selected.val()){
                $.each(others, function (index, value) {
                    value.style = 'display:none';
                });
            }

        });
    </script>
    <?php else:?>
        <style> .others{display: block;} </style>
        <script>
            let btnChange = $('#change-cat');
            let selectSub = $('.field-mainCat').hide();
            let selectMain = $('.field-subcat-id').hide();

            btnChange.on('click', function () {
                this.style = 'display:none';
                selectSub.show();
                selectMain.show();
            });
        </script>
    <?php endif;?>
</div>

backend/views/tovar/_search.php
<?php

use kartik\depdrop\DepDrop;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TovarSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tovar-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'main_category')->dropDownList($mainCategory,
        ['id' => 'mainCat', 'prompt'=>'Выберете категорию'])->label('Главная категория')?>

    <?= $form->field($model, 'subcategory_name')->widget(DepDrop::classname(), [
        'options'=>['id'=>'subcat-id'],
        'pluginOptions'=>[
            'depends'=>['mainCat'],
            'placeholder'=>'Выберете подкатегорию',
            'url' => Url::to(['/tovar/subcat?filter=true'])
        ]
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton('Найти', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tovar/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Tovar */

$this->title = Yii::t('app', 'Добавить товар');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Товары'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tovar-create">
    <div class="kt-portlet ">
        <div class="kt-widget14">
            <div class="kt-widget14__header">
                <h3 class="kt-widget14__title">
                    <?= Html::encode($this->title) ?>
                </h3>
            </div>
            <div class="kt-widget14__content">
                <div style="width: 100%">

                <?= $this->render('_form', [
                    'model' => $model,
                    'subcategory' => $subcategory,
                    'mainCategory' => $mainCategory,
                    'img' => $img
                ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tovar/index.php
<?php

use backend\assets\DataTableAssets;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Товары');
$this->params['breadcrumbs'][] = $this->title;
DataTableAssets::register($this);
?>
<div class="tovar-index">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    <?= Html::encode($this->title);?>
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <?= Html::a(Yii::t('app',
                        '<i class="la la-long-arrow-left"></i> Назад'), Yii::$app->request->referrer,
                        ['class' => 'btn btn-clean btn-icon-sm']) ?>
                    <div class="dropdown dropdown-inline">
                        <?= Html::a(Yii::t('app',
                            '<i class="flaticon2-plus"></i> Довавить товар'), ['create'],
                            ['class' => 'btn btn-brand btn-icon-sm']) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="kt-portlet__body">
    <?php Pjax::begin(); ?>

    <?= $this->render('_search', ['model' => $dataSearch, 'mainCategory' => $mainCategory])?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $dataSearch,
        'tableOptions' => [
//            'id' => 'kt_table_1',
            'class' => 'table table-striped- table-bordered table-hover table-checkable'
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            [
                'attribute' => 'name',
                'value' => function ($model) {
                    return Html::a($model->name, Url::to(['view', 'id' => $model->id]));
                },
                'format' => 'raw',
            ],
            'subcategory_name',
            [
                'attribute' => 'sort',
                'value' => function ($model) {
                    return Html::input('text', 'sort', $model->sort, ['class' => 'sort form-control', 'data-id' => $model->id]);
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'created_at',
                'value' => function ($model){
                    return date('d.m.Y', $model->created_at);

                }
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' => '<div class="dropdown">
                                      <a class="btn-lg" style="color: #0f0f0f; cursor: pointer;" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <i class="fas fa-ellipsis-v"></i>
                                      </a>
                                      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                        {view}
                                        {update}
                                        <div class="dropdown-divider"></div>
                                        {delete}
                                      </ul>
                                    </div>',
                'buttons' => [
                    'view' => function ($url) {
                        return Html::a(
                            '<i class="far fa-eye"></i> '
                            . Yii::t('app', 'Просмотр'),
                            $url,
                            [
                                'title' => Yii::t('app', 'Просмотр'),
                                'data-pjax' => '0',
                                'class' => 'dropdown-item',
                            ]
                        );
                    },
                    'update' => function ($url) {
                        return Html::a(
                            '<i class="fas fa-pencil-alt"></i> '
                            . Yii::t('app', 'Редактировать'),
                            $url,
                            [
                                'title' => Yii::t('app', 'Обновить'),
                                'data-pjax' => '0',
                                'class' => 'dropdown-item',
                            ]
                        );
                    },
                    'delete' => function ($url) {
                        return Html::a(
                            '<i class="fas fa-trash"></i> ' .
                            Yii::t('app', 'Удалить'),
                            $url,
                            [
                                'title' => Yii::t('app', 'Удалить'),
                                'data-pjax' => '0',
                                'class' => 'dropdown-item',
                                'data' => [
                                    'confirm' => Yii::t('app',
                                        'Вы уверены, что хотите удалить?'),
                                    'method' => 'post',
                                ],
                            ]
                        );
                    }
                ],
            ],
        ],
    ]); ?>
        </div>
    <?php Pjax::end(); ?>

</div>
    <script>
        jQuery(function($) {
            $('.sort').on('change', function () {
                $.post('/tovar/sort?id=' + $(this).data('id'),{
                    sort: $(this).val()
                }, function (date) {

                })
            })
        });
    </script>
    <script>
        $(document).ready(function() {
            $('#kt_table_1').DataTable({
                "language": {
                    "lengthMenu": "Записей на странице _MENU_",
                    "zeroRecords": "Записей не найдено",
                    "info": "Страница _PAGE_ из _PAGES_",
                    "infoEmpty": "Нет записей",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "search" : "Поиск"
                }
            });

        } );
    </script>

backend/views/tovar/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Tovar */

$this->title = Yii::t('app', 'Обновить товар: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Товар'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Редактировать');
?>
<div class="tovar-update">
    <div class="kt-portlet ">
        <div class="kt-widget14">
            <div class="kt-widget14__header">
                <h3 class="kt-widget14__title">
                    <?= Html::encode($this->title) ?>
                </h3>
            </div>
            <div class="kt-widget14__content">
                <div style="width: 100%">

                <?= $this->render('_form', [
                    'model' => $model,
                    'subcategory' => $subcategory,
                    'mainCategory' => $mainCategory,
                    'img' => $img,
                    'imageView' => $imageView
                ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/tovar/view.php
<?php

use common\models\Images;
use yii\helpers\Html;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Tovar */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Товары'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<div class="tovar-view">
    <div class="kt-portlet ">
        <div class="kt-widget14">
            <div class="kt-widget14__header">
                <h3 class="kt-widget14__title">
                    <?= Html::encode($this->title) ?>
                </h3>
            </div>
            <div class="kt-widget14__content">
                <div style="width: 100%">

                <p>
                    <?= Html::a(Yii::t('app', 'Редактировать'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                    <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                            'method' => 'post',
                        ],
                    ]) ?>
                </p>

                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'name',
                        'short_name',
                        'subcategory_name',
                        'item_values',
                        'description',
                        'sort',
                        [
                            'attribute' => 'img_id',
                            'value' => function ($model) {
                                $image = Images::findOne($model->img_id);
                                return 'http://cc59539.tmweb.ru/uploads' . $image->path .'/'. $image->name .'.'. $image->ext;
                            },
                            'format' => ['image',['width'=>'100','height'=>'100']],
                        ],
                        'updated_at',
                        'created_at'
                    ],
                ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>